model: "diffusion_lora"
base: "stabilityai/sd-1-5"         # latent diffusion base
resolution: 256
train_steps: 20000
batch: 8
lr: 1e-4
lora_rank: 8
class_conditional: true
mask_conditioning: false
dp:
  enabled: true
  target_epsilon: 10
  delta: 1e-5
  max_grad_norm: 1.0
out_dir: "out/diffusion_lora"
seed: 123
